version: "3.9"
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 199.203.7.0/24
          gateway: 199.203.7.1
services:
  app: 
    container_name: MyMoviesCatalog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      net:
        ipv4_address: 199.203.7.101

    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 199.203.7.100
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: